title: Kranthi Kumar Bitra
description: Enterprise Solutions Architect with over 13+ yrs of experience on design, system integration, and strategic thinking. Drive the technical team to adopt to shift-left mindset, to choose right design and adhere to industry best practices.​​
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
