title: Kranthi Kumar Bitra
description: Engineering practice leader expertise in strategic thinking, system integrations and design
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
